language: node_js
version: 1.0
sudo: false
node_js:
  - 12
install:
  - npm install
script:
  - npm run build
deploy:
  edge: true
  provider: npm
  email: "hamidrezakks@gmail.com"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master